### ISSUE TITLE
USB Connection Lost popup should offer 'Stop' option

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#121]
When the 'USB Connection Lost' message appears, only 'Continue' is available. 'Stop' would be a good option as well, no?
For that matter, even the Z-axis popup would benefit from an option to stop what we're doing.

**Comment by BarbourSmith** [comment]
I completely agree. 

To make things easier both objects are instances of the notificationPopup.py class so if we change one, they are both going to change anyway 😄

**Comment by BarbourSmith** [comment]
added
