### ISSUE TITLE
Save settings to persist through version changes.

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#124]
Settings are currently saves within the directory that gets replaced by a version change. Save the somewhere that will persist.

**Comment by BarbourSmith** [comment]
+1

I've had trouble with this in the past because every platform is different BUT Kivy has us covered with the user_data_dir option, see the very bottom of this page: https://kivy.org/docs/api-kivy.app.html

**Comment by blurfl** [comment]
That looks like it, do you want me to work on it?

**Comment by BarbourSmith** [comment]
Yes! Absolutely! If you want to take it on, that would be fantastic!

**Comment by blurfl** [comment]
Great, I’m on it!

**Comment by BarbourSmith** [comment]
@blurfl  took care of this 👍 👍
