### ISSUE TITLE
allow machine dimensions to be entered in metric or imperial

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/GroundControl#126]
add a units button to ground control and let someone enter the measurements in whatever units they are measured in and let the software do the conversion

**Comment by BarbourSmith** [comment]
This is with regard to entering the machine dimensions, correct?

**Comment by davidelang** [comment]
Yes, when you enter the mchine dimensions into Ground Control, it should have a 
metric/imperial toggle and do the conversion between the two internally.

David Lang

**Comment by BarbourSmith** [comment]
@davidelang 

Since the new calibration accepts measurements in either mm or inches, are you comfortable with closing this?

**Comment by davidelang** [comment]
yes.
