### ISSUE TITLE
Indicate that the machine state is on 'Hold'

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#143]
When 'Hold' has been clicked, change the text of the "Run" button from "Run" to "Resume". This will show that the hold command is in effect and how to leave that state to resume cutting.

**Comment by BarbourSmith** [comment]
@blurfl Does PR #169 add the behavior you are imagining?

**Comment by blurfl** [comment]
Yes, it's just right. Will you close this or shall I?

**Comment by BarbourSmith** [comment]
Fantastic! I can close it because I'm here, but you should always feel free to close things you feel ready to close
