### ISSUE TITLE
Z axis zero on HOME or STOP button push

### ISSUE THREAD

**Issue by blsteinhauer88** [MaslowCNC/GroundControl#153]
If there is a chain skip or other reason one would need to STOP instead of pause the cut. I noted the bit was still engaged with the wood after I then told it to go HOME. This caused a cut across the materials. Add code to first zero the Z acid on a stop command, and then a 0.1 safety depth on HOME command.

**Comment by BarbourSmith** [comment]
Great idea!

**Comment by BarbourSmith** [comment]
Should be added in #155 , power is out in our building right now so I can't test it, but I will merge as soon as I can test it
