### ISSUE TITLE
make this gcode run in GC

### ISSUE THREAD

**Issue by hannahebteagle** [MaslowCNC/GroundControl#157]
hello! :) attached is the ZIPPED version of the .nc that won't open correctly yet in Ground Control :)))
[untitled folder 2.zip](https://github.com/MaslowCNC/GroundControl/files/880214/untitled.folder.2.zip)

**Comment by BarbourSmith** [comment]
Fixed in #170

**Comment by BarbourSmith** [comment]
There appear to be some scaling issues with the files, but that's not a Ground Control issue

**Comment by BarbourSmith** [comment]
The latest changes appear to have made this code not work again, more investigation is needed

**Comment by BarbourSmith** [comment]
First thing is this file doesn't specify units (G20/G21) or coordinate system (G90/G91) at the beginning which is poor form. Ground Control guesses that the units are the same as the last file opened, which isn't ideal, but there's not a lot else we can do about it.

**Comment by BarbourSmith** [comment]
Fixed again in PR #193
