### ISSUE TITLE
Rasp Pi Touchscreen keyboard types double characters

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#160]
Using a keyboard to enter values in the settings produces double characters per keystroke. Typing  a '1' produces '11'. This makes entering values impractical.

**Comment by TheRiflesSpiral** [comment]
Check the config.ini file for multiple or generic HID input types.

[input]
mouse = mouse
mtdev_%(name)s=probesysfs,provider=mtdev
**hid_%(name)s=probesysfs,provider=hidinput
%(name)s=probesysfs,provider=hidinput**

The last two lines in this file cause USB HID input to be handled by two providers. Try deleting the last line.

**Comment by blurfl** [comment]
Once again, you've done it. 👍 Thanks for your help.
For posterity, on my (generic) kivypie setup. I edited 
/home/sysop/.kivy/config.ini and commented out the line:
%(name)s=probesysfs,provider=hidinput

Note that this change also corrected an issue with mouse-clicking which affected the mouse but not the touchscreen, causing double-clicks instead of single clicks.

**Comment by TheRiflesSpiral** [comment]
I'll update the instructions to include this edit in KivyPi.

**Comment by BarbourSmith** [comment]
Beautiful work everyone!

**Comment by BarbourSmith** [comment]
Has this issue been resolved?

**Comment by blurfl** [comment]
I remember some discussion about this after @theRifleSpiral posted the fix on the forum.I bumped the thread to see whether anyone thinks it should stay open. It certainly worked for me, “close” is my vote.

**Comment by TheRiflesSpiral** [comment]
If you're running python under root (sudo python main.py from the ~/GroundControl directory) Kivy will use the root's config.ini file, not sysop. I updated the wiki to include an edit to both the sysop and root users.

**Comment by BarbourSmith** [comment]
Fantastic! Thank you for updating the wiki to include both edits, and good sleuthing to figure out what was going on!
