### ISSUE TITLE
Rasp Pi Mouse cursor click location misaligned

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#161]
Using a mouse in GroundControl there is a blue dot for a cursor. The hot spot when the mouse is clicked is above and to the left of the cursor image.
 A comment on the forum suggests that there might be "a folder that holds the image files that appear during touches and when the cursor moves… "

**Comment by TheRiflesSpiral** [comment]
The doc describing the touchring module is here: https://kivy.org/docs/api-kivy.modules.touchring.html

**Comment by TheRiflesSpiral** [comment]
Here's a solution... It's a bit of a hack: replace the image "defaulttheme-0.png" in your [Kivy]/data/images folder with the image below.

![defaulttheme-0](https://cloud.githubusercontent.com/assets/26791099/24512830/3c1a9388-1535-11e7-9c9d-8b672922f7bc.png)

This will put a fancy Maslow mouse cursor that is more obvious where the click will happen.

If you're just looking for a simple mouse cursor, use this file: 

![defaulttheme-0 1](https://cloud.githubusercontent.com/assets/26791099/24513043/d4fd7930-1535-11e7-8bc6-a2f7fa58b37e.png)

**Comment by BarbourSmith** [comment]
Is there a way we can make this easier for everyone? Possibly put this file into the Ground Control GitHub repo so that it can be moved into the proper location with a single command during the setup process?

Love the Maslow mouse cursor 😀 

Great fix.

**Comment by TheRiflesSpiral** [comment]
Absolutely. I'll work on that after lunch.

**Comment by blurfl** [comment]
That's the bunny! Thank you @TheRiflesSpiral 💯 ! I like your Maslow cursor :) 👍 
For posterity, on the kivypie image (mine, but I think it's generic) the location to put the defaulttheme-0.png file is:
/usr/local/lib/python2.7/dist-packages/kivy/data/images

**Comment by BarbourSmith** [comment]
Has this issue been resolved?

**Comment by blurfl** [comment]
I would say yes.
