### ISSUE TITLE
New features need to be documented on wiki page

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#196]
New features in the 'advanced' tab need to be documented on the wiki.

**Comment by BarbourSmith** [comment]
Great point. Thank you for filing an issue for it!

**Comment by BarbourSmith** [comment]
I've updated the wiki page [here](https://github.com/MaslowCNC/GroundControl/wiki/Ground-Control-Users-Guide#actions-menu)

**Comment by BarbourSmith** [comment]
I'm going to close this issue
