### ISSUE TITLE
NC file too big to load due to "Follow the Path" lettering

### ISSUE THREAD

**Issue by blsteinhauer88** [MaslowCNC/GroundControl#200]
Here is the file that would not load.
[Bench Back For Kids (2).zip](https://github.com/MaslowCNC/GroundControl/files/923125/Bench.Back.For.Kids.2.zip)

**Comment by BarbourSmith** [comment]
I'll dig into it and see what I can find out! Thank you for sharing it.

**Comment by BarbourSmith** [comment]
@blsteinhauer88 Are you sure that's the one that doesn't load? That one looks to me like it's just the outline, but it seems to load ok

![outline](https://cloud.githubusercontent.com/assets/9359447/25097013/936c9ffc-2357-11e7-8d68-7aefc5fa8284.JPG)

**Comment by blsteinhauer88** [comment]
[Bench Back For Girls Final.zip](https://github.com/MaslowCNC/GroundControl/files/926406/Bench.Back.For.Girls.Final.zip)
Try This one, big!

**Comment by BarbourSmith** [comment]
That looks like the one :-)

I'm seeing 50,000+ lines, and it doesn't load

**Comment by BarbourSmith** [comment]
This one is going to be a little tricky. I've got figure out what's slowing everything down and it seems to have to do with the way the underlying graphics system is processing everything. 

As a note to my future self, the first thing to look into is to if rendering the whole thing as one polyline iwth 50,000+ points will render faster than 50,000 individual lines. 

I've added an error popup, and at least the file will try to load now, but on my computer GC gets VERY slow. Added in #205

**Comment by BarbourSmith** [comment]
Support for big files (up to 60,000 lines) added in #279 

![big file](https://cloud.githubusercontent.com/assets/9359447/26029961/b11ec4ee-37f7-11e7-8645-50da94a184b3.JPG)

Thanks for suggesting the change, sorry it took me so long to make it. 

Good to close?

**Comment by blsteinhauer88** [comment]
Yes looks good!
