### ISSUE TITLE
Zencodersteps in main.py value does not match Firmware

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#210]
firmware CNC_Functions.h uses 7650, main.py uses 7550. The value in main.py gets written in a new .ini file

**Comment by BarbourSmith** [comment]
Good catch! Let me check the data sheet to see which one is right.

**Comment by blurfl** [comment]
The firmware one has the formula in the excellent comment.

**Comment by BarbourSmith** [comment]
Thank you for pointing that out! And thank you to past me for putting the comment!

**Comment by BarbourSmith** [comment]
Fixed in #211 , Ok to close?

**Comment by blurfl** [comment]
That was quick, a new rodeo record!
