### ISSUE TITLE
Logic for calculate chain length automatic

### ISSUE THREAD

**Issue by shy21grams** [MaslowCNC/GroundControl#222]
When selecting stop during the automatic chain length process, undesirable values are stored. It causes the next x/y move to sled outside of machine bounds. In my case it extended the chains past their mounting points and straightened the hog ring before I could pull the power.

Possible solution could be to not save the values if the stop button is activated.

**Comment by BarbourSmith** [comment]
Great catch and clear description of the problem!

Thank you for finding that.

**Comment by BarbourSmith** [comment]
I think that we have resolved this 👍
