### ISSUE TITLE
Raise Z before transit on "Return to Center"

### ISSUE THREAD

**Issue by nwrancher** [MaslowCNC/GroundControl#224]
Currently when "Return to Center" is pressed, Maslow moves Z to 0 before moving to center.  Z should retract to safety height prior to transit.

**Comment by blurfl** [comment]
I've been bitten by this one, too. I had an idea for a fix and Bar improved on it. It still needs a touch of polish, but may soon be ready for release. See here:
https://github.com/MaslowCNC/GroundControl/pull/220

**Comment by BarbourSmith** [comment]
This behavior was added by @blurfl in #230, just in time for this week's release 👍
