### ISSUE TITLE
Ghost crosshair when stepping through code.

### ISSUE THREAD

**Issue by blsteinhauer88** [MaslowCNC/GroundControl#227]
There used to be a crosshair pop when you pause and push the step back or forward button, so it was easy to identify where you were stepping to. It is gone now. Can it be put back?

**Comment by BarbourSmith** [comment]
Great point, I know what happened and it should be a quick fix. Thanks for pointing out the problem!

**Comment by BarbourSmith** [comment]
Added back in in #228 , Thanks again for finding the problem (It was a one letter fix 😀 )
