### ISSUE TITLE
change open file process to be more efficient

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/GroundControl#232]
to open a file it first reads every file in the directory (and apparently rather inefficiently) and then displays every one of them, with no ability to sort/search them, or type a filename

My home directory has >1200 files in it, and having to go through these graphically to find a file is horribly slow

**Comment by BarbourSmith** [comment]
I completely agree. I'm not sure what the solution is because the file chooser is built into Kivy so I didn't create it. The right solution could be to use the native file chooser in tkinter?

**Comment by BarbourSmith** [comment]
Although that won't work on android anymore...

**Comment by johnbenweber** [comment]
The native kivy filechooser can handle file extension filtering, see PR #265.

**Comment by johnbenweber** [comment]
I think this issue can be closed.
