### ISSUE TITLE
Calibrate - step 4 of 7 has odd button values

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#247]
Extend 10mm, retract 1mm, retract 10mm, retract 100mm

Retract 100mm is not useful, Extend 1mm and Extend 100mm would be useful.

**Comment by BarbourSmith** [comment]
Good point, they are strange values.

I liked Retract 100 because at that point in the process my chain was really long from having just spanned the motors, did you not have that issue?

**Comment by blurfl** [comment]
Oops! I just lifted the chain and moved the end. While doing that I trod on the USB cable and pulled that out, so I had to start over. I did the step for 12 o’clock then skipped ahead to step 4.

 If we’re reeling the chain back in , I want ‘Retract 500’ or ‘Retract 1000’ ! My chain was almost completely extended :)

**Comment by blurfl** [comment]
I _really_ like the way you used the measurement of step 4 as the start of the 'Calibrate Chain Length' so that the left chain was already partly measured. Very nice!

**Comment by BarbourSmith** [comment]
:-) shucks

**Comment by blurfl** [comment]
Should the Stop button be 'Stop motor' instead of 'Stop cut'? Otherwise this looks ready to close. 💯 👍

**Comment by BarbourSmith** [comment]
Should be changed 👍

**Comment by blurfl** [comment]
Looks good 💯
