### ISSUE TITLE
Calibration step 7 of 8 causes confusion between inches and mm modes

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#254]
If starting with the machine in inches mode, after running the test cuts the machine seems to be left in metric mode and GroundContol in inches. The 'Return to Center', 'Home' and arrow buttons, as well as the 'Z in/out' controls seem to move in mm instead of inches. Changing to mm mode and using 'Home' causes the z motor to z-out but never z-in again but the sled does not move. Using an arrow causes the sled to move and restores the 'Home' function.

**Comment by BarbourSmith** [comment]
Great catch!

**Comment by blurfl** [comment]
Starting in mm mode has the same effect. Using an arrow to move the sled restores normal operation.

**Comment by BarbourSmith** [comment]
The machine was getting left in relative position mode so the move home command of X0Y0 didn't do anything. Ground Control was also not being switched from Inches to MM mode, only the machine was. Both are now fixed...I didn't see this issue at all until you pointed it out. Thank you.

**Comment by blurfl** [comment]
👍
