### ISSUE TITLE
Configure step 2 of 8 - negative value for motor-to-motor measurement

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#257]
Just ran this cal a second time, and when I advance to step 5 I see a negative value (-0.98) for motor-to-motor spacing.
I'm going to correct this in the manual settings...

**Comment by BarbourSmith** [comment]
There was a pretty silly bug in the way that measuring was done, but I'm pretty sure I got this one. I'm going to close it, but let's keep an eye on it and see if we see the issue again.

I'm going to start working my way through all these excellent suggestions.

**Comment by blurfl** [comment]
👍
