### ISSUE TITLE
View Gcode and scrolling zooms out

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#264]
If you use View Gcode and scroll though a long file, if you don't scroll back up, you can't see you worksheet any more. You have to zoom back in, the same amount that you have scrolled down in the Gcode. Not a big issue, but worth mentioning. I got confused for a second.

**Comment by johnbenweber** [comment]
Yeah, would be good to fix this. This is mostly why I implemented the "reset view" button under the "view gcode" button.

**Comment by johnbenweber** [comment]
Should be fixed, see PR #280.
