### ISSUE TITLE
Setup Machine Dimensions - Step 4

### ISSUE THREAD

**Issue by shy21grams** [MaslowCNC/GroundControl#274]
Step 4 is missing a button to stop motors. The chain got wrapped up and I had to pull the cable from the motor to stop it. Thanks!

**Comment by davidelang** [comment]
there should probably be a big 'STOP' button on every screen, in the same place.

shopbot also uses the spacebar to stop everything when the machine is running.

David Lang

**Comment by BarbourSmith** [comment]
Good point, I will add that right now.

Spacebar is a great idea.

I will add both.

**Comment by BarbourSmith** [comment]
I have added a stop button to step #4

**Comment by shy21grams** [comment]
Issue resolved in #275.
