### ISSUE TITLE
GC0.72 - if uninitialized, motors won't respond until an .nc file has been opened.

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#288]
The machine controls are unresponsive until an .nc file is opened. Rolling back to the previous version works as expected.

**Comment by BarbourSmith** [comment]
Great to know! I will look into what is causing this, hopefully before the release tomorrow.

**Comment by BarbourSmith** [comment]
Should be fixed in #290.

The issue was that the machine was checking if it had space for the next line of code, but there was no next line to look at

**Comment by blurfl** [comment]
💯 👍 Welcome back :)
