### ISSUE TITLE
PR#295 - Terminal shows 'Unable to check buffer' error at end of cut

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#296]
I have a moderately curvy file that clearly showed the chattering issue mentioned several days ago in these links:
http://www.maslowcnc.com/forums/#!/general:new-gc-release-72/well-cutting-in-the-week-sp
http://muut.com/u/maslowcnc/s3/:maslowcnc:2g9h:img_0827.jpg.jpg

I downloaded GC and Firmware (ref GC#295 and Firmware#230 'sun-moon...') and ran my file and I can report that the chattering is so much reduced as to be practically indistinguishable. 👍 

At the end of the cut, however, I no longer have control of the sled without quitting and rerunning GC. 😞  Looking at the terminal window I see the following message repeating:
Unable to check buffer
[PosError:1.01,0.62,160]

Unable to check buffer
[PosError:0.40,0.36,160]

The file, 'F-hole.nc' is zipped and attached:
[F-hole.nc.zip](https://github.com/MaslowCNC/GroundControl/files/1033182/F-hole.nc.zip)

**Comment by BarbourSmith** [comment]
I experienced this also. I will look into it.

I was able to regain control by clicking "Stop" several times. Not ideal.

I'm glad to hear that you found the chattering issue to be much less. It's good to get a second opinion. 👍 👍

**Comment by BarbourSmith** [comment]
Thank goodness we've solved this one 😃
