### ISSUE TITLE
Prev and Next buttons in 'Actions -> About' crashes GC

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#299]
Both buttons cause GC to crash with "TypeError: 'NoneType' object is not callable".
Perhaps these buttons are obsolete.

**Comment by BarbourSmith** [comment]
I see this too. I think these buttons were added to allow you to flip through the pages of the gcode file in view -> gcode.

Good catch.

**Comment by johnbenweber** [comment]
Ah, I didn't notice there was another use of scrollabletextpopup when I did that. See PR #305.
