### ISSUE TITLE
Kivy installation fails to build on OSX 10.12.1: Clang error

### ISSUE THREAD

**Issue by braedenf** [MaslowCNC/GroundControl#301]
I am having an issue compiling GroundControl on my Macbook. The issue is with Kivy failing to compile due to Clang errors: _error: command 'clang' failed with exit status 1_.

Is anyone else experiencing this issue?

**Comment by BarbourSmith** [comment]
Yes! I spent like a week trying to figure that out and gave up. If you find a solution, I would love to know.

**Comment by braedenf** [comment]
I solved the problem: All I had to do was install the latest Command Line Tools 8.3.2 for XCode, then it installed with the steps in the readme no problems whatsoever!

**Comment by BarbourSmith** [comment]
Darn, I tried that with no luck. At least it worked for you 👍 

Ok to close the issue?

**Comment by braedenf** [comment]
Yeah, I repeated my steps on two other macs but got another issue with pygame not windowing properly, however Kivy compiled fine. Have you tried deleting the command-line tools filder before re-installing it?

**Comment by andymillernz** [comment]
On the issue with pygame and the window resizing issue on OSX I've added a note to the bottom of the wiki [mac install instructions](https://github.com/MaslowCNC/GroundControl/wiki/Mac) on how to ensure you are using SDL2 and not pygame for the Window manager - see [GL Reloading Section](https://kivy.org/docs/api-kivy.graphics.html) in the Kivy docs..

**Comment by BarbourSmith** [comment]
Great! Thanks for updating the docs!

**Comment by braedenf** [comment]
Yeah, I fixed the issue as well by doing: pip install https://github.com/kivy/kivy/archive/master.zip then it could find SDL2 fine :)

**Comment by mrfugu** [comment]
This issue can be closed.
