### ISSUE TITLE
Truncate gcode values at 4 digits beyond the decimal point.

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#310]
Some gcode creation programs write values to 8 or 9 digits beyond the decimal point.

 This is way beyond our precision and impacts serial transmission, buffering and string handling.
GroundControl should truncate those values and keeping four digits beyond the decimal point seems about right to me.  

Universal Gcode Sender has a configuration option to choose the number of digits but that could be an enhancement for the future.

**Comment by davidelang** [comment]
another useful thing would be to calculate the distance between one location and 
the next, and if the difference is too small, skip the command (will really help 
when the source used too many line segments for a curve)

k

**Comment by johnbenweber** [comment]
Wrote a fix for truncating floats to 4 digits, see PR #339.

**Comment by blurfl** [comment]
Nicely done, thanks for all the effort!
