### ISSUE TITLE
Z-axis calibration runs in mm when GC is set for inches, moves 1 inch when 1mm button clicked.

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#321]
Set GC GUI to inches mode, go to Calibrate Machine Dimensions, skip to Step 7 without running any other steps. Buttons read in mm but machine has not yet been sent G21. Z-axis moves 1" or 0.1" rather than 1mm or 0.1mm. Not sure whether the issue is the button text or the mismatch between the text and the movement value.

**Comment by BarbourSmith** [comment]
Fantastic catch!

Nobody wants to move 1 inch 😁 

I'll fix it right now.

**Comment by BarbourSmith** [comment]
Should be fixed in #322 thanks for the catch!

**Comment by blurfl** [comment]
Yup, quite a surprise 🙂

**Comment by blurfl** [comment]
Fixed in #322
