### ISSUE TITLE
Calibration Routine glitch

### ISSUE THREAD

**Issue by blsteinhauer88** [MaslowCNC/GroundControl#324]
With the latest fw/GC my sled is having trouble finding center, I have an error ring and it just climbs the board. I decided to Wipe the eprom, reload the FW and calibrate like new. When I get the the first step to align the gear, the left motor will move 1degree, but the right motor turns about a full turn of the gear. I cannot align the gear to finish the steps.  I closed, reloaded all again, and it is confirmed that the right motor 1 degree cw or ccw movement it turning a full turn of the motor.

**Comment by blsteinhauer88** [comment]
Additional, It does not matter if you press cw or ccw it turns cw a full turn.

**Comment by blurfl** [comment]
I too see the error ring get larger the farther from the center. GC76, Frimware76.

**Comment by blsteinhauer88** [comment]
Try using the calibration and see if the right motor turn full turn instead of 1 degree to confirm.

**Comment by blurfl** [comment]
I find that the right motor doesn't move in response to either CW or CCW button; the lift motor responds as expected. Too, the error circle grows as the sled leaves the center, shrinks as it returns to center.

**Comment by blsteinhauer88** [comment]
That is what I have had this morning too. Thanks

**Comment by BarbourSmith** [comment]
I had this behavior last week, but I thought I fixed it. Thank you for letting me know it's still a problem. I'll dig into it again and see what I can find.

**Comment by BarbourSmith** [comment]
As a quick work around something I've seen fix this issue is to run the manual calibration once, then do the automatic calibration

**Comment by blsteinhauer88** [comment]
I tried manual calibration.  Still have the problem with the motor turning full turn and only in the cw motion.

**Comment by GeroBH** [comment]
I did not try the GC76, Frimware76 yet, was hoping to do testpattern tomorrow. With the two previous GC/FW I had similar issues with aligning the sprockets. Chatter on the right motor while turning the left, that would result eventually in bringing the sprocket off the 12:00. Trying to align right sprocket moved the left more clear and with less chatter.

**Comment by BarbourSmith** [comment]
@blsteinhauer88 You are running the v0.76 firmware and Ground Control, right?

I was seeing this same exact behavior sometimes before Wednesday and it was one of the things I tried to fix in the Wednesday release (although it seems like I might not have got it completely sorted)

**Comment by BarbourSmith** [comment]
Do you have any advice for how to make the problem happen? I've been trying to make the problem happen again this morning and I can't get it to behave that way. I've tried unplugging the machine while it's moving, pressing 'stop' part way through the calibration process and starting over.

Mine doesn't behave perfectly, sometimes one of the motors will twitch a little, but I'm not able to get it to do the full rotation behavior

**Comment by blsteinhauer88** [comment]
I loaded GC 75 with no change.  I loaded Firmware 73, and GC 76 works.  The problem in is the new firmware.

**Comment by BarbourSmith** [comment]
Oh woah, thanks! That's great to know. So I actually broke it this week, not made it better? Ooops! 😨

**Comment by BarbourSmith** [comment]
I'm at a little bit of a loss as to what to do next, because until I can replicate the issue it's going to be really hard for me to figure out what's going on.

@GeroBH will you try doing the calibration process with v0.76 also and see if you can give us more insight into what is happening?

**Comment by BarbourSmith** [comment]
@blurfl Do you have any advice? It seems like everyone might be seeing the issue EXCEPT me

**Comment by blurfl** [comment]
I’m away from the shop until later in the day. I’ll see what I can find then.

**Comment by blsteinhauer88** [comment]
@bar, did you get it to happen?  Today I had to restart the computer for an update to windows.  I loaded the new .76 versions, and It told me it did not know where it was, and to run the calibrate.  I ran the calibrate machine and immediately had the problem zeroing the gears.  I was able to compete the calibration with GC 76 and Firmware 73.  I will reload  FW 76 and see how it performs.

**Comment by BarbourSmith** [comment]
After I couldn't get the issue to happen I got sucked in to #300 , I'll have another go right now

**Comment by bar** [comment]
@blsteinhauer88 mhh?

**Comment by blsteinhauer88** [comment]
![screenshot 2017-06-16 15 23 01](https://user-images.githubusercontent.com/26512036/27246640-c3aafa9a-52a7-11e7-8fcb-f9535b5d8372.png)
Bar, I ran David Lang's test pattern, (results to post later) 
I uploaded firmware, .76.  I moved it only 10 inches.  I took a screenshot.  You can see it is off by .2 both directions.  I don't know if it will zero itself.

**Comment by bar** [comment]
@blsteinhauer88 you are talking to the wrong person...

**Comment by GeroBH** [comment]
Will have some hours time to run calibration and hopefully some cuts with a brand new Linux Manjaro in about 8 hours.

**Comment by blsteinhauer88** [comment]
@bar, sorry wrong dude.

**Comment by blsteinhauer88** [comment]
![screenshot 2017-06-16 17 13 39](https://user-images.githubusercontent.com/26512036/27248358-3858a20c-52b7-11e7-8e89-791096b3f0dc.png)
Here is what happend when I pushed Home, and my sled went to center, then traversed to about +5,+4.

**Comment by BarbourSmith** [comment]
Hmm. I replaced the error circle with a second set of cross hairs so now Ground Control will give us the white cross hairs to show where the machine wants to be, and the red cross hairs to give us an estimate of where it actually is. If you download the very latest firmware and GC from GitHub it might give us a better sense of what is going on
![capture](https://user-images.githubusercontent.com/9359447/27248952-e739958a-52bf-11e7-9313-6e3c12f3d7b8.JPG)

**Comment by blurfl** [comment]
I noticed that on the files I'm testing - I like it!

**Comment by BarbourSmith** [comment]
Did it give any better information about what's going on? When you get that big error circle, where is the red cross hairs?

**Comment by blsteinhauer88** [comment]
Cool. loaded GCmaster and this is what happened. 
![screenshot 2017-06-16 18 28 49](https://user-images.githubusercontent.com/26512036/27249075-d2d7df6e-52c1-11e7-98eb-7828aef63c66.png)

**Comment by blurfl** [comment]
I had that, did the manual chain length cal and it straightened out. It also might be a fluke of the screen draw, if white is drawn first, red covers it over. They lined up differently depending on my zoom level.
I found that the red circle and crosshairs gave interesting info, maybe alarming. If the red accurately indicates where the cutter is and the white is where it should be at that same moment, I'm seeing differences. Kind of hard to decide how big as there's no scale to go by. I found myself wishing that there was a 'keep the crosshairs centered' mode so I could zoom in and watch the cut up close -future enhancement-. Also wished for a little bar graph of the error value, with a high-water marker -future enhancement-.

**Comment by BarbourSmith** [comment]
Both great suggestions!

The inner circle on the cross hairs is 1mm so when you are zoomed way in you can still get a sense of scale.

I agree that the error is more than I expected. It looks like because the red cross hairs are always lagging behind the white ones, it almost follows the correct path, but we're probably cutting some corners in ways we don't want to be. Certainly something to work on!

**Comment by blsteinhauer88** [comment]
To continue where I left off @BarbourSmith, my last screenshot was just installing the GC master.  It showed the red cross hairs in about the postition the sled was sitting.  I hit the home button and GC did this:
![screenshot 2017-06-17 07 57 22](https://user-images.githubusercontent.com/26512036/27253955-2e662176-5333-11e7-97ba-2235d256ee2c.png)

BUT! the sled did this and I had to pull power so it would not tear the frame and sled apart.
![photo jun 17 7 57 35 am](https://user-images.githubusercontent.com/26512036/27253960-4b22e506-5333-11e7-964d-b5b7f59d8a22.jpg)

I am going to back load FW .73

**Comment by GeroBH** [comment]
Calibration was no fun with the new linux and FW0.76.GC0.76. No chance to complete. 2 times I had negative values for Motor Spacing and vertical offset and very diferent ones. https://dl.dropboxusercontent.com/s/g4rb024bin6t40c/calib1.jpg?dl=0 https://dl.dropboxusercontent.com/s/f5s5o2qwaamrr9g/calib2.jpg?dl=0
Retracting left chain would somtimes extend very short and then retract. You need to look close to see that. After manual chain length and entering the dimensions buy hand, I can move the sled around. No trace of the red circle here. Z-Moves make both motors chatter to an extent that the chains are chivering.

**Comment by BarbourSmith** [comment]
I've got some great news. Using Hannah's computer and the other machine, I'm seeing the same (I think) behavior you guys are. Hopefully I can track down what's going on this way.

**Comment by BarbourSmith** [comment]
I think I see what's going on. I'm working on a fix right now 👍

**Comment by BarbourSmith** [comment]
I've got something that took me through the calibration process twice on the system that didn't work before. 

When anyone has a chance, check out the latest firmware and Ground Control from Git Hub and let me know if it fixes the issue for you too. 

The issue was with the way the calibration process handled unexpected starting conditions. Last week I added some code to the firmware which would try to catch when something funky was going on and reset the values, but it was running at times we didn't want it to and messing things up.

Now the process is handled by Ground Control. When you click the "Begin" button, the machine is set to a known state, so in theory we should always start the calibration process with everything set right.

Let me know if it works!

**Comment by GeroBH** [comment]
@Bar "latest firmware and Ground Control from Git Hub" <-- still don't know if that is the the green download button, or the latest under 'releases' (assume they are the same) and if the .tar.gz always gets updated the same time as the .zip, kindly advise. Got used to go for the 'releases' as they have the version in the compressed file name and I am archiving now.

**Comment by BarbourSmith** [comment]
Good question 😀 

The "latest" is always the green download button, the latest version under "releases" will be the version from the last Wednesday

The .tar.gz and .zip files will always be updated at the same time (they are generated automatically) when the release comes out.

**Comment by davidelang** [comment]
the releases are not the latest, they are what is tagged as a release on 
wednesdays

The green 'clone or download' will grab the very latest version that has been 
pushed to github (bar may have a newer copy on his machine, but github has no 
way of knowing that)

**Comment by bar** [comment]
@GeroBH I have no idea what you are talking about :) you are talking to the wrong person

**Comment by davidelang** [comment]
apologies, please be patient with us (and keep reminding us as someone new makes the mistake of doing @bar instead of @BarbourSmith  (especially those of us who respond via e-mail and so don't have the github web interface prompting is for auto-completion of the names as we type)

**Comment by blsteinhauer88** [comment]
Bar, I loaded your latest FW and GC.  The calibration routine seemed to work.  The right motor did not do full turns.  I did not finish the routine and went back to GC.  I told the sled to travel up 4 inches and each time it went down.  
![file jun 18 7 21 48 pm](https://user-images.githubusercontent.com/26512036/27267212-c15d6330-545b-11e7-89b4-83cf571e096b.jpeg)
It ended up here.  When I hit return to center, it also travels down.  ????

**Comment by BarbourSmith** [comment]
What was happening before was that not only were the motors not turning the right amount, the values that were being stored in settings were way off (I had a negative spacing between the motors on mine)

I would try either manually entering values you know are good in the settings, or going through the whole calibration process to make sure that the machine has good values

**Comment by BarbourSmith** [comment]
Would anyone be willing to take a look at the version currently on GitHub to check if the calibration process is working?

I've tested it out on my end, but having a second set of eyes on it would be really valuable.

You'll know you are running the right version because the version number will be 0.77

![version 0 77](https://user-images.githubusercontent.com/9359447/27366588-f044172e-55fb-11e7-8ef3-fefc4c7ae3bb.JPG)

Thanks everyone for your patience while I've been sorting this one out!

**Comment by blurfl** [comment]
I’ll give it a go, report back in a bit.

**Comment by blurfl** [comment]
Part way through, I notice that in step 7 when raising and lowering z, the sled also moves in the xy direction, small seemingly random jumps. Z axis moves as desired, though. FWIW, I noticed this same behavior before I started the cal steps, just setting z when I first started GC77/FW77.
So fr the other steps are as normal, now for the cuts!

**Comment by blurfl** [comment]
I just completed the cal sequence, three cuts to arrive at 0.3mm difference between horizontal and vertical.

**Comment by ladyhawke13** [comment]
During calibration my left motor will only adjust CCW. When I select move left move CW 1 degree the motors hums but no actual movement.

**Comment by BarbourSmith** [comment]
@ladyhawke13 are you still seeing this issue?

**Comment by ladyhawke13** [comment]
It was consistently doing that through my calibration - unfortunately I can't test it to see if it's still doing it at the moment - everything's in pieces! However, I'm hoping to get everything back together by the weekend so hopefully I can let you know in a few days.

**Comment by BarbourSmith** [comment]
Perfect! Keep me posted if the issue persists, and we'll track it down
