### ISSUE TITLE
Add version as top level variable in main.py for Android APK building

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#337]
When building an Android APK out of GroundControl it is required to have a "version" variable at the top level in the main.py. See the example in the [building executables](https://github.com/MaslowCNC/GroundControl/wiki/Building-Executables) for Android documents.

Example:
```python
version = 0.78
```
or even a dynamic version would probably be better:
```python
version = str(self.data.version)
```

**Comment by jbnimble** [comment]
Turns out the latest version of Kivy and Buildozer no longer use the main.py "version" variable and instead use the buildozer.spec "version" property.

**Comment by BarbourSmith** [comment]
👍 👍 👍 

Let me know if you get it to build, it's on my todo list but a ways off 😀

**Comment by jbnimble** [comment]
@BarbourSmith, Built fine, updated wiki instructions. Able too execute on older Android tablet and opened various menus. Did not try to load gcode, and no hardware to test serial connection yet. Thinking of writing a script that takes care of editing the buildozer.spec and running the buildozer commands. Where could a script pull the version number?
