### ISSUE TITLE
simulation requests

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/GroundControl#342]
I'm glad to see this, a couple requests

1. make there be some way to zoom the grid

2. make the errors able to be entered as numbers, not just via the sliders.

**Comment by davidelang** [comment]
I see from reading the code that you can zoom with a mouse

**Comment by davidelang** [comment]
I'm looking to see about printing the machine actual dimensions vs theoretical dimensions

**Comment by BarbourSmith** [comment]
Great recommendations!

You might also be interested in the `doSpecificCalculation()` function. It's not currently being called, but I was using it to take exact measurements at a known place

**Comment by BarbourSmith** [comment]
I believe that you added these @davidelang 👍 👍
