### ISSUE TITLE
Calibration Machine Dimensions Step 7 Settings

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#355]
Allow the user to enable/disable the Z-Axis and to set/update the Z-Axis related settings values on Step 7.

**Comment by BarbourSmith** [comment]
These are all great suggestions. Thank you for suggesting all of them. Its a lot of changes and some of them are easier to implement than others, but I'm going to have a go at each one.

**Comment by BarbourSmith** [comment]
This has been added 😀 and it's much better than it was before you suggested it
