### ISSUE TITLE
Calibration Machine Dimensions All Steps

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#357]
There is a lot of words on the calibration steps, and they are useful, but users are excited to get this part finished, so can skip important parts of the calibration. For example I missed the fact that I needed to re-cut the test pattern until the numbers matched.

It might be good to distill the verbiage as succinctly as possible, with short and direct verbiage. Maybe even some warnings when the user tries to click the "Re-Cut/Stop-Cut" when they have not entered values or the cut has finished. If they have clicked those buttons at the wrong time then it means they did not read and understand the instructions and a warning that explains they need to enter the measured values to remind the user what to do next.

**Comment by BarbourSmith** [comment]
I totally agree with this. I think at this point we've done a good job of distilling the text down, but it is something to constantly keep an eye on
