### ISSUE TITLE
Calibration Machine Dimensions Step 8 Visual Cue

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#359]
Highlight the lines that are cut in the images with the tape measure, so the user knows what to expect. When I first tried to perform calibration without the Z-Axis I did not understand the directions that the +/- meant for turning the Z-Axis manually, so my calibration cut was all over the place, and I did not understand which of the lines I was meant to cut.

**Comment by BarbourSmith** [comment]
This is handled much better now with a more clear description and the cuts highlighted:

![image](https://user-images.githubusercontent.com/9359447/35707233-d0eee67e-075d-11e8-81ed-902fab1575c4.png)

I'm going to close it
