### ISSUE TITLE
Ground Control Open File

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#360]
Default to "List View", the "Icon View" you can't read the name of the file. I see 5 characters of the beginning of the file and the last 3 characters plus ".nc" of the end of the file name in Icon View, which is not useful.

An alternative is to have a setting to allow defaulting one or the other views.

**Comment by BarbourSmith** [comment]
I believe the default is now list view:

![image](https://user-images.githubusercontent.com/9359447/34751555-45b1a39c-f562-11e7-8e58-2acbf3aa0070.png)
