### ISSUE TITLE
Goto Number Entry

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#362]
The "Goto" button opens a number entry, but there is no explicit "Close" button for those that might be using a touch screen an easy way to cancel to action by clicking a button would be convenient.

**Comment by BarbourSmith** [comment]
This is true for all of the number entry popups

**Comment by blurfl** [comment]
Doesn't the 'Done' button qualify? if the field is blank it returns no change...

**Comment by BarbourSmith** [comment]
Great point @blurfl you are 💯 right. I vote to close.
