### ISSUE TITLE
Motor continues to run after notification for z-depth adjustment is shown

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/GroundControl#371]
The L/R motors continue to operate even after the notification is shown the a z-axis adjustment needs to be made.

This was experienced on v.81

**Comment by blurfl** [comment]
To be clear, lines of gcode were executed beyond the line with the z-axis change, in the manual z-axis mode, right?

**Comment by JDogHerman** [comment]
Yes that is what I saw.

**Comment by BarbourSmith** [comment]
Are you still seeing this behavior? I think it may have been an issue which was fixed around .83 or so

**Comment by JDogHerman** [comment]
I am not able to reproduce this with v 0.87
