### ISSUE TITLE
Return to home causes the motors to continue after being held

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/GroundControl#373]
v0.81

Ground Control was running some g-code. I put it in hold after it asked for a depth change. I then told Ground control to return to home. It returned to home then continued to run gcode from the new position. 👎

**Comment by BarbourSmith** [comment]
I believe that this issue has been fixed by the removal of the "Hold" option in the z-axis popup. Would you agree?

**Comment by JDogHerman** [comment]
Without a hold button it seems to be fixed but, how would I cancel the job?

**Comment by krkeegan** [comment]
Clicking Stop will cancel the job.

I think this isssue is likely ripe for closing

**Comment by JDogHerman** [comment]
If the z axis dialog is up there is no way that I see to cancel the job. The stop button along with all other buttons (except for continue) are inaccessible. The only way I see to actually quit would be to close ground control.

**Comment by krkeegan** [comment]
Ahh, yes, I see the issue now.  I guess we need a stop button in the zaxis dialog?

**Comment by BarbourSmith** [comment]
This has been added 👍 👍 🌹
