### ISSUE TITLE
Shortcut or button to center work area

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#375]
Using a laptop with a touchpad sometimes causes the work area to move "off screen", and then I can't find it again. I would like a way to to cause the work area to be in the middle of the viewing area.

**Comment by davidelang** [comment]
ideally, such a 'find me' button would also zoom so that the entire part that's 
being cut fills the screen (not the entire work area as the piece being cut 
could be very small)

**Comment by blurfl** [comment]
‘Actions/Reset View’ accomplishes part of this. There is no keyboard equivalent. Adding more buttons to the front screen gets in the way for users with smaller displays, though.

**Comment by jbnimble** [comment]
Does actions > reset view effect the currently running cut?

**Comment by blurfl** [comment]
I don’t know for sure, but I don’t think so...

**Comment by BarbourSmith** [comment]
No, it shouldn't have an effect on the cut, it just moves the preview to the center

**Comment by jbnimble** [comment]
If that is the case, then that is good enough for me, and this issue can be closed, unless someone else needs more.
