### ISSUE TITLE
Some on-screen type _very_ small

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#382]
Not certain when this cropped up, but it was correct in release 0.82.
<img width="800" alt="screen shot 2017-07-31 at 4 23 36 pm" src="https://user-images.githubusercontent.com/1851315/28802771-105f0970-760d-11e7-9dfa-9fb015af586d.png">

**Comment by BarbourSmith** [comment]
Oh, I'm glad you pointed that out. I've been messing with exactly that today 😬

**Comment by blurfl** [comment]
Furthermore, the top two error sliders draw part of their text ouside the box - only 'Error' shows for each.

**Comment by davidelang** [comment]
what sort of system are you using? what screen resolution?

**Comment by blurfl** [comment]
The system is OS X. The labels drawn with screen resolution 1024x640; anything large shows the issue.

**Comment by blurfl** [comment]
I’ve played around and made some progress. I’ll post a commentwith details later, after I get four more post holes dug 🙂

**Comment by blurfl** [comment]
I swear I had both Windows and OSX displaying the Simulation control labels correctly last night. Tonight Windows is displaying wrong. I'm unable to get these things pounded into github for a day or so, so some observations:

I did find that Window.size[0] is width, [1] is height. Printing window.size on my OSX system shows the retina display size:
window w, h
(5120, 2706)

The tiny text is fixed by font_size: '10sp' as you suggested

On OSX I was having luck formatting the simulation labels so:
            Label:
                text: "Motor Spacing\nError: 0mm"
                text_size: self.width, sp(self.height)
                font_size: (self.height - 6)/2
                halign: 'left'
                valign: 'middle'
                id: motorSpacingErrorLabel

Sorry for the disjointed message, I hope something in it is of use>

**Comment by BarbourSmith** [comment]
Fixed in #565! Way to go @blurfl 👍 👍
