### ISSUE TITLE
Change color of gcode visual line after cut

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#392]
The visualization of the gcode is always white, it would be neat if the color could change after the line has been executed.

**Comment by blurfl** [comment]
How would lines that will receive multiple passes work?

**Comment by jbnimble** [comment]
Good point, not sure. The idea was to give a quick visual way to tell how much is completed and how much is left to go.

**Comment by blurfl** [comment]
There’s a % complete and line number number on the right. I think the percent is based on line number rather than the time it takes to cut any one line.

**Comment by jbnimble** [comment]
It is certainly a visual eye candy feature, and not required for operation. If the consensus is there are better  things to spend time then I'm fine with closing it unresolved.

**Comment by BarbourSmith** [comment]
I'm going to close this for now because I am worried that it would require a lot of ram when loading large files
