### ISSUE TITLE
Left Justify X,Y,Z status

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#393]
When the X,Y,Z status values have varying sizes of decimal numbers they jump left and right, and should probably be modified so the values are justified (left or right) and the X,Y,Z labels stay in the same location on the screen.

My personal preference would be that the decimal stay in the same position, and the XYZ labels stay in the same position, and the numbers grow/shrink around those fixed labels.
For example:
```
X:  23.48747
Y:   2.3773
Z:  -1.338
```

**Comment by BarbourSmith** [comment]
Should be added in #422 !

The readout now looks like this:

![image](https://user-images.githubusercontent.com/9359447/30495705-dfb78694-9a01-11e7-9b58-9606fa12e16e.png)

Great suggestion @jbnimble ! 

Let me know if I missed anything 😀
