### ISSUE TITLE
Clicking stop when already stopped causes the motor to turn on.

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/GroundControl#399]
Observed with v 0.87 

The motors will sometimes just hum and other times the output shaft turns.

**Comment by JDogHerman** [comment]
The position markers don't move during this time even-thou the motor output shaft turns.

**Comment by krkeegan** [comment]
This may be related to the Firmware issue [#293](https://github.com/MaslowCNC/Firmware/issues/293).  Although I don't know why the motors would go from off, to back on again when pressing stop.

**Comment by BarbourSmith** [comment]
Any command sent to the machine will cause the motors to energize for two seconds to hold their position...is this behavior wrong in the case of the stop command?

**Comment by krkeegan** [comment]
We should check to see if this still happens.  I don't think clicking stop after the motors are stopped causes them to turn on anymore.

**Comment by davidelang** [comment]
It seems like it would probably cause more grief to try and special case this.

**Comment by BarbourSmith** [comment]
Best possible answer @krkeegan I just tested it and you are right pressing stop does not engage the motors anymore
