### ISSUE TITLE
Motors will continue to run even after GroundControl has closed.

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/GroundControl#401]
If GC is closed while a job is being run the motors will continue to run. This seems like an important safety concern.

**Comment by davidelang** [comment]
how would the firmware know that GC was closed? it's just following the last 
instruction it was sent, and doesn't know if GC was closed or if it's just 
about to send a new command (and it can take a while to finish executing a 
command)

Given that there is other software that can send commands to the maslow, it's 
not clear that the maslow should shutdown if GC exits anyway.

**Comment by JDogHerman** [comment]
Maybe a heartbeat should be setup. This would monitor if communication was lost from the application closing or the USB becoming unplugged.

**Comment by BarbourSmith** [comment]
If the USB becomes unplugged the machine will stop immediately, but if GC is closed it will finish executing the current line of gcode then shut itself down and save it's position. I feel like this is the desired behavior (it's the same as GRBL which is the industry standard right now). How do we feel about closing this one?

**Comment by blurfl** [comment]
I agree, OK by me.

**Comment by davidelang** [comment]
I think it makes a lot of sense to match grbl

**Comment by BarbourSmith** [comment]
Oops, I didn't mean to reopen 😬
