### ISSUE TITLE
Kinematics posts chain re-cal required if no gcode file open

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#402]
Opening a gcode file is a workaround.

[Edit] On my system it appears to matter whether the gcode file is in inches (G20) or mm (G21). If inches, the workaround is valid. If the file is in mm, the dialog appears with chain lengths 0.00 when GC is started.

A discussion on the [forum](http://forums.maslowcnc.com/t/impossible-to-cut-a-piece-without-losing-calibration/454/49?u=blurfl)

**Comment by krkeegan** [comment]
I think I have this fixed, just need to run a few tests.

The difference between MM and inches occurs because MM is the default setting, so no command is sent to the machine resulting in the same error as if no gcode file was specified.
