### ISSUE TITLE
Rookie issue - can't access git repository

### ISSUE THREAD

**Issue by servant74** [MaslowCNC/GroundControl#420]
On RaspberryPi I get 
fatal: unable to access 'http://github.com/MaslowCNC/GroundControl.git/' Could not resolve host github.com 

I know this is uber basic, but I could do with a hand hold... Thanks in advance.

**Comment by servant74** [comment]
After 2 hours I resolved it... command was

get clone https://www.github.com/maslowCNC/GroundControl.git

Not exactly as in the wiki (missing the "www."  Sorry to bother anyone, but I was very frustrated.

**Comment by davidelang** [comment]
please update the wiki with the correction.

**Comment by krkeegan** [comment]
It was the https not the www that made the difference
