### ISSUE TITLE
Make calibration process touch screen compatable

### ISSUE THREAD

**Issue by BarbourSmith** [MaslowCNC/GroundControl#443]
The calibration process is the only step with requires a keyboard to enter numbers for the distances. It would be great to be able to run Ground Control entirely without a keyboard

**Comment by skiz** [comment]
@BarbourSmith Would this be step 4 of 'Setup Machine Dimensions'?

**Comment by BarbourSmith** [comment]
Yes, sorry for the poorly worded description 😬
