### ISSUE TITLE
Auto calibration - last step can't back up

### ISSUE THREAD

**Issue by bdillahu** [MaslowCNC/GroundControl#449]
I got to the test cut screen, started and then clicked "stop cut" (ran into a physical issue with the machine - sled hit the bottom)... decided to just skip it for now and hit "skip". Then decided to go back and look at something. Hit "back" and it goes back and the see the screen for an instant, then it jumps back to the end/finish screen. You can't go back to that test cut page.

**Comment by BarbourSmith** [comment]
I know what's going on here. Clicking the back button takes you to the test cut window for the quadrilateral kinematics which isn't what we want so it jumps forwards again. I will fix this, thanks for the heads up
