### ISSUE TITLE
Actions -> View Gcode without any gcode Crashes

### ISSUE THREAD

**Issue by skiz** [MaslowCNC/GroundControl#453]
There needs to be a check if there is any Gcode is loaded when clicking this button.
The application crashes.  It should just show an alert that there is no gcode or a blank screen.

**Comment by skiz** [comment]
File "/Users/jmartin/Projects/GroundControl/UIElements/viewMenu.py", line 118, in show_gcode
     titleString = 'Gcode File: ' + self.data.gcodeFile +'\nLines: '+str(line+1)+' - '+str(lineNum)+' of '+str(len(self.data.gcode))
 UnboundLocalError: local variable 'line' referenced before assignment

**Comment by BarbourSmith** [comment]
Great catch and thank you for posting the full error also! 👍 👍
