### ISSUE TITLE
Setup Machine Dimensions - Step 10 of 10

### ISSUE THREAD

**Issue by jbnimble** [MaslowCNC/GroundControl#455]
After selecting Stop Cut there is no way to restart the cut. If for example you realize the first cut did not go deep enough because the Z-Axis zeroing was incorrect, and you go back to fix the Z-Axis, but now you can't start the cut over again.

It would be nice to be able to either send the sled to Home, or just restart the cut from its current location.

**Comment by BarbourSmith** [comment]
Great point!

What if I made it so that it just re-enabled the "Run Test Cut" button after stop is pressed so that pressing that button would restart it

**Comment by jbnimble** [comment]
That would be fine with me, also having it start the test cut over again from the start would be fine.

**Comment by BarbourSmith** [comment]
> What if I made it so that it just re-enabled the "Run Test Cut" button after stop is pressed so that pressing that button would restart it

This has been added! Excellent suggestion 👍 👍
