### ISSUE TITLE
Actions -> Calibrate Chains Length - Automatic does not finish at 0,0

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#460]
It looks like though logic to move to 0,0 at the end of chain calibration in the full calibration sequence, it wasn't added to the end of the the automatic calibration on the Actions page. See discussion [here](https://forums.maslowcnc.com/t/i-put-my-linkage-kit-together/854/42?u=blurfl).
Possibly add a 'Finish' button which would call root.finishChainCalibration()?

**Comment by BarbourSmith** [comment]
I think this is part of a larger issue that we have the same code implemented twice. Really there should be a single instance that is referenced in both places, right? That way a change to one will show up in both places

**Comment by blurfl** [comment]
You're right, that's always the best. Got to be able to use the Automatic Chain calibration without entering the full calibration sequence, though.

**Comment by BarbourSmith** [comment]
Fixed in #477 👍
