### ISSUE TITLE
Triangular Calibration Drops Sled to Floor

### ISSUE THREAD

**Issue by madgrizzle** [MaslowCNC/GroundControl#465]
Reference: [https://forums.maslowcnc.com/t/calibration-linkage-alternate-sled-design/1093/12](url)

I looked at the code and didn't see any glaring mistakes, but the sled drops to the lower left corner during the final step of calibration and if using the temporary frame, rolls around on the floor.

Perhaps X0, Y0 that's determined during the calibration process is off.  I didn't readily see anything in the calibration code that would cause it to drop so low.

**Comment by BarbourSmith** [comment]
I'm looking into this right now

**Comment by madgrizzle** [comment]
Isn't the kinematics settings under advanced settings not maslow settings:

This line is from the calibration routine:
self.data.config.set('Maslow Settings', 'kinematicsType', self.chooseKinematicsType.text)

**Comment by BarbourSmith** [comment]
I've made this change and some other small fixes. When I ran the calibration process on a fresh install of Ground Control (deleting the .ini file in your home directory to wipe all the settings to the default) it didn't go off the bottom for me.

When you have a chance will you try the latest version? I'm happy to compile one for you if you aren't set up to run python directly
