### ISSUE TITLE
it's not clear that exiting the calibration process part way through can cause trouble

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#466]
Some steps of the auto calibration process put the software into relative mode, or alter the previous settings. Advancement through the calibration steps in other than the default order can result in lost or improper settings.
 Reference issue #459

**Comment by skiz** [comment]
Would it make sense to restore the original settings on exit unless they explicitly save changes from the last page?   showing current & new values could be beneficial, but the screen is already quite crowded on a pi 7"

**Comment by blurfl** [comment]
I agree on both items. 👍🏻

**Comment by madgrizzle** [comment]
This could be the cause of some of the strange issues I had during calibration early on.  I had many failed attempts and if I aborted or skipped some steps, sometimes it behaved weirdly.  I suggest that perhaps each step of the calibration issue a command to ensure the controller is in its proper (relative or absolute) mode, regardless of the mode of the previous step.

**Comment by blurfl** [comment]
I think the issue I was seeing was caused by the 'Begin' button in Step1 - it executes gcode "B06 L0 R0" which tells both axes that they are at the first link of the chain. There is a comment "This prevents strange behavior when rotating each sprocket to 12:00". 
 With the present code, clicking this button clobbers your chain calibration whether that was what you intended or not.
I'll do some testing, but I believe recent changes to kinematics and the chain calibration procedure make this 'Begin' button behaviour unnecessary.

**Comment by BarbourSmith** [comment]
I agree that we've made significant improvements to this area and it's probably safe to remove that command. It was in there to prevent issues which were showing up when the axis target and actual location were far apart at the beginning of the calibration process which is a state which could be left from a previous failed calibration attempt. 

We are much less likely to end up in that situation now so I say go for it and take it out!

**Comment by BarbourSmith** [comment]
@blurfl , is this issue good to close or is more needed do you think?

**Comment by blurfl** [comment]
I'd say it's done.
