### ISSUE TITLE
Fuison 360 export as Grbl does not render because of missing spaces

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#473]
https://forums.maslowcnc.com/t/first-2-cuts-on-the-maslow/1215
Proven for me and might need to be addressed
Edit: I remembered when I've seen it the first time. I made the G-Code for the 15 squares in a spread-sheet and exported to .csv. Then renamed to .nc
It had no 'spaces', would not render but cut

**Comment by blurfl** [comment]
Within gcodeCanvas.py1 reloadGcode() in the area of lines 128-133 is where the gcode disk file gets read into GC. We currently get rid of spaces between the opcode characters and their parameter digits, this might be the place to make sure that every opcode character has one space in front of it if it isn't at the start of the line...

**Comment by BarbourSmith** [comment]
Good to close?

**Comment by blurfl** [comment]
Sure thing👍
