### ISSUE TITLE
Make two buttons for choosing kinematics type

### ISSUE THREAD

**Issue by BarbourSmith** [MaslowCNC/GroundControl#478]
The way that that you select your kinematics type is confusing in the calibration process. Right now it's a drop down which used to make sense when the triangular kinematics were a weird fringe project, but now that they are being used we need to make this step more clear.

The desired behavior is that the step has two buttons, one for triangular and one for trapezoidal. Clicking either button will adjust the settings and take you to the next step.

Original mention is here:
https://forums.maslowcnc.com/t/lots-of-issues-calibrating/1257/10

**Comment by davidelang** [comment]
or a slider toggle from one to the other
