### ISSUE TITLE
after PR#485, groundcontrol fails to run

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#486]
after PR#485, groundcontrol fails to run, posts thew following error:

` Traceback (most recent call last):
   File "main.py", line 38, in <module>
     from UIElements.diagnosticsMenu   import   Diagnostics
   File "/Users/scottsmith/Documents/GitHub/MaslowCNC/GroundControl/UIElements/diagnosticsMenu.py", line 5, in <module>
     from UIElements.measureMachinePopup              import    MeasureMachinePopup
   File "/Users/scottsmith/Documents/GitHub/MaslowCNC/GroundControl/UIElements/measureMachinePopup.py", line 338
     except:
           ^
 IndentationError: unindent does not match any outer indentation level
`

**Comment by blurfl** [comment]
spacing got changed on lines 334-337...

**Comment by BarbourSmith** [comment]
Great catch. The PR was all good, but somehow the merge broke things. I will fix ASAP

**Comment by blurfl** [comment]
👍💯

**Comment by BarbourSmith** [comment]
We had a rogue space running loose! 😁

**Comment by krkeegan** [comment]
odd, sorry about that guys.  Not sure how that happened.

**Comment by BarbourSmith** [comment]
It definitely wasn't your fault, the pull request itself worked great. It think we both edited that section of code and the automatic merge process decided to add an extra space for some reason 🤷‍♂️

**Comment by krkeegan** [comment]
odd, never seen anything like that before, I guess it keeps you on your toes.

**Comment by blurfl** [comment]
Thanks again for the performance enhancers 👍
