### ISSUE TITLE
Double character in 

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#507]
PR#503 has introduced an issue where after changing the MM/INCHES in the number input characters typed are doubled.

**Comment by BarbourSmith** [comment]
WEIRD! I would not have expected that. I will look into that right away! Thanks for the catch!

**Comment by BarbourSmith** [comment]
I'm not seeing the same behavior, help me better understand what you are seeing

We're talking about the numbers typed in here showing up twice, right?

![image](https://user-images.githubusercontent.com/9359447/34273778-a4f6586a-e64a-11e7-860a-7b89892dd95f.png)

**Comment by blurfl** [comment]
Right. I open the dialog, type a number, change mm to inches, backspace and type.

**Comment by BarbourSmith** [comment]
I still can't make it happen 🤕

**Comment by BarbourSmith** [comment]
Maybe it's platform dependant?

**Comment by blurfl** [comment]
I've just replicated the issue on Win10 and a second instance of OS X. Seems to be related to clicking in the number field:
1. open the 'machine movement' change window
2. type '12'
3. click in the number field
4. type '34' - see '3344'

**Comment by BarbourSmith** [comment]
Got it! I totally see it too now. I was missing the type in the window field step

**Comment by BarbourSmith** [comment]
I have a proposed solution in #509
