### ISSUE TITLE
Triangular Calibration vertical placement slider raises sled too far

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#510]
With the vertical placement slider of the Triangular Calibration step at the top of its range (in the neighborhood of +388mm judging by the log), after making the cuts, the sled tries to move 500mm above that level. That would be above the top of a 1220mm sheet.
 If the cut level is above Y=0, make the sled move in the negative Y directionn after the cut instead?

**Comment by BarbourSmith** [comment]
Yes! I think that is an excellent suggestion

**Comment by blurfl** [comment]
The move is currently 500mm, that gets pretty close to the edge when starting from the middle. How about lowering that to 400?

In triangularCalibration.py, change line 41 from:

        self.data.gcode_queue.put("G0 X-900 Y500 ")

to:

        if self.testCutPosSlider.value <= 0:
            self.data.gcode_queue.put("G0 X-900 Y400 ")
        else:
            self.data.gcode_queue.put("G0 X-900 Y-400 ")

**Comment by BarbourSmith** [comment]
Yes, I think 400 should be good. My reason for moving the sled was to get it out of the way to make it easy to measure

**Comment by davidelang** [comment]
the longer the baseline, the more accurate the resulting calibration will be.

**Comment by blurfl** [comment]
The number under discussion determines how far the sled moves in the Y direction after cutting the marks, to get out of the way for measuring.
