### ISSUE TITLE
CG 1.02 dark theme is using positionIndicator.color black, making it invisible

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#530]
My guess is that in gcodeCanvas.py line 44 should somehow be set (1,1,1) for the dark theme, instead of (0,0,0)
OS linux
FW 1.02
GC 1.02

**Comment by BarbourSmith** [comment]
This one should be an easy fix too. Thank you for filing these @GeroBH. The issues you file are always well written and point to exactly what needs to change.
