### ISSUE TITLE
B07 (Wipe Eeprom) results in -> error: Invalid gcode ID:78

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#532]
OS: Linux
FW: 1.02
GC:1.02

->Actions -> Advanced -> Wipe EEPROM
Result in GC=
B07
error: Invalid gcode ID:78

**Comment by BarbourSmith** [comment]
Great! Thanks for finding that! I think this should be an easy fix 😀

**Comment by krkeegan** [comment]
Yes.  This is because the B07 command is gone.  We have to decide what of the $RST= commands we want to be called by GC:

$RST=$ -- wipes eeprom of settings only
$RST=# -- wipes all eeprom used by maslow
$RST=* -- wipes the entire 4Kb eeprom

**Comment by BarbourSmith** [comment]
I vote for $RST=* 

I feel like the wipe EEPROM is kind of the nuclear option which just takes you back to a clean slate. What does everyone else think?
