### ISSUE TITLE
Show default value next to each setting

### ISSUE THREAD

**Issue by BarbourSmith** [MaslowCNC/GroundControl#543]
It would be nice to show a default value next to each setting to make it a little more clear what has changed

**Comment by blurfl** [comment]
kivy's settings module limits the 'very easy' solution to editing the "desc" of each option to add something like
"desc": "The horizontal distance between the center of the motor shafts in MM. - default value 1234.5"
That's inelegant as it doesn't automatically capture changes made to the default values later in main.py build_config().

**Comment by madgrizzle** [comment]
I'm not a python programmer, so bear with me.  Could you create the default value dictionaries early on and then when creating the JSONs for Kivy settings, use str.format to substitute values from it?  I found this on stackoverflow.  Solution #3 seems like it might work:

[https://stackoverflow.com/questions/36590496/how-to-substitute-value-for-a-variable-in-a-json-in-python](url)

The same dictionaries could then also be used to populate the defaults in config.setdefaults.  This way, there's only one place the defaults are stored.

**Comment by BarbourSmith** [comment]
I like that idea a lot 👍

**Comment by blurfl** [comment]
@madgrizzle, your link was right to the point. I'm afraid I 'stole' it 😉 to learn a bit more python programming. I'll pull my PR back if you're working on a patch for this issue. 🙂

**Comment by madgrizzle** [comment]
Keep going.. I wasn't working on it.. just threw out a suggestion.

⁣Sent from BlueMail ​

**Comment by BarbourSmith** [comment]
This is now a thing! Great work @blurfl
