### ISSUE TITLE
Simulation calculations values - float or integer

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#571]
Most of the constants used in the Simulator are without decimal values. Adding '.0' to them makes a noticeable difference in the results, visible in the values calculated with zero error. Should these constants be explicit floats? I'm not sure how Python2.7 handles them...

**Comment by BarbourSmith** [comment]
Yes! Great catch. I think making them explicit floats is an excellent idea

**Comment by blurfl** [comment]
Good-o, I'll try to keep this PR from going crossways 😉

**Comment by blurfl** [comment]
Solved in pr #574
