### ISSUE TITLE
Simulation results values displayed to 12 decimal places

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#573]
How many decimal places are really needed when showing the calculated error in the Simulator? Three seems enough, four would overcome the lack of rounding of formatted floats.

**Comment by BarbourSmith** [comment]
I'd even say two is probably good. Measuring to two in the real world is usually a bit optimistic 😀

**Comment by davidelang** [comment]
depends on if you are mm on in, for mm, 2 digits is enough, for in, 4 would be 
better. doing 4 and not worrying about units seems like the easy way out.

**Comment by blurfl** [comment]
Ok, I'll up it to 4. Thanks for the insight

**Comment by blurfl** [comment]
Addresses in PR #574
