### ISSUE TITLE
Windows Portable does not have the "gcodeForTesting" directory

### ISSUE THREAD

**Issue by MeticulousMaynard** [MaslowCNC/GroundControl#588]
I was attempting to run the "Calibration Benchmark Test" this weekend and Ground Control gave me a "cannot find G-Code" error. 

![benchmarkerror](https://user-images.githubusercontent.com/1744214/35234871-917c7d48-ff70-11e7-927a-623b8cf5c873.PNG)

Upon further inspection, the "gcodeForTesting" directory that is present in the main repository is not there in the Windows Portable release. I downloaded the repository as a .zip file and added the "gcodeForTesting" directory to my Windows portable directory. When trying to run the test after adding the folder, I still get the same error. Is the benchmark program in the right directory?

This is what my Ground Control directory looks like right now (the benchmark file is in the selected folder):

![groundcontrol](https://user-images.githubusercontent.com/1744214/35234884-97052aee-ff70-11e7-82bb-a86243cd1fc8.PNG)

**Comment by BarbourSmith** [comment]
Great catch! That's totally my fault. I will make sure the build script includes it right now. Sorry!

**Comment by BarbourSmith** [comment]
Fixed in #589 😀
