### ISSUE TITLE
Display velocity for Maslow and current g-code line on the screen

### ISSUE THREAD

**Issue by thormj** [MaslowCNC/GroundControl#592]
Figuring between Z and not connected, I'd like an indicator that says:
Vel: 30 ipm  | 30 ipm

Where the first number is from Maslow, and the 2nd number is from the current line of g-code.

**Comment by thormj** [comment]
Is there a (preferably auto-generated) list of g-code commands somewhere?

**Comment by thormj** [comment]
I'll take this one and run with it for a while...

**Comment by BarbourSmith** [comment]
I believe that there is a list of supported commands on the wiki page, but it is not automatically generated (which would be slick)

We've been talking about setting up circle CI integration to automate tasks like that which I am happy to help with on my end

**Comment by BarbourSmith** [comment]
I think you nailed this one, good to close?

**Comment by thormj** [comment]
Yep.
