### ISSUE TITLE
After Z cal, move to safe height

### ISSUE THREAD

**Issue by thormj** [MaslowCNC/GroundControl#595]
Since it was touching the board, I was wondering if it was going to lift up before moving to the cutting position.  When you leave the Z-cal step (if using motors), raise the router to the "safe height"

**Comment by BarbourSmith** [comment]
Good point! It would be easy to send a lift command right after that step is completed

**Comment by BarbourSmith** [comment]
Is this guy good to close?

**Comment by blurfl** [comment]
I would say, yes
