### ISSUE TITLE
Hold coordinates in GC to resume after disconnect

### ISSUE THREAD

**Issue by BarbourSmith** [MaslowCNC/GroundControl#6]
"Greetings all! I love my CNC mill but it is driving me up the wall with this issue about disconnects. I had hoped that the reconnect feature would solve this, it's kinda frustrating to bump the table and have an hour + of cut time go down the drain.

Is there any way at all to store the current coordinates so that when I unplug my CNC mill and plug it back in (after restarting ground control), that the most recent coordinates are saved? This must be doable in ground control, even if not in the CNC software itself."

**Comment by MakesmithTech** [comment]
Maybe the solution is to store the machine's coordinates only when the servos disconnect at the end of the run in the machine's eeprom.

**Comment by MakesmithTech** [comment]
The plan:

When the servos disconnect, after being idle the machine will store it's position into EEPROM, every time the machine boots, it will load it's position from EEPROM.

On the GC side, if the machine disconnects partway through a run, GC will store the current gcode line in the settings file and pause the gcode run. When the machine reconnects or when GC is restarted the program can be resumed.

**Comment by MakesmithTech** [comment]
Firmware side complete.

**Comment by BarbourSmith** [comment]
This behavior has been in place for a while now, should have closed this
