### ISSUE TITLE
Z-axis popup should save the units  setting on entry and restore it on exit

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/GroundControl#615]
if I change the units in the z-axis popup while halted during a run, the popup returns with the units changed, affecting the rest of the cut. The popup should save and restore the units that the cut file established.

**Comment by BarbourSmith** [comment]
I didn't understand the first time I read this issue description, but I get it now and it's a great point 👍

**Comment by blurfl** [comment]
This was addressed in PR #611
