### ISSUE TITLE
Red & Green start & stop circles

### ISSUE THREAD

**Issue by bazzacad** [MaslowCNC/GroundControl#656]
I'm not sure if this is a bug or a design intent, but the red & green start & stop circles seem to be opposite of what I'd think they should be. If you think from the cutting point of view, the start of the cut is a red circle & the stop of the cut is the green circle, I'd think they'd want to be the other way around. But if you're thinking from the traverse point of view, then they're correct, green start of traverse, red stop. I tend to think form the cutting point of view. 

![2018-02-26 14_34_54-groundcontrol](https://user-images.githubusercontent.com/23222121/36700260-058c65e6-1b04-11e8-97ba-d19fff87fb8a.png)
of traverse.

**Comment by BarbourSmith** [comment]
Woah! I was thinking of them as red being dangerous because the bit is lowering, and green being safe because it's lifting up

**Comment by blurfl** [comment]
"red being dangerous because the bit is lowering, and green being safe because it's lifting up" That's the way I looked aty it... Also red stands out more, and that's where the cutting begins.

**Comment by bazzacad** [comment]
OK, never mind ;-)

**Comment by BarbourSmith** [comment]
Let's leave it as is just because it doesn't seem like a pressing issue, but I'm glad you brought up the idea of red and green possibly indicating start and stop. That makes a lot of sense.

**Comment by krkeegan** [comment]
I believe that the simulator in Fusion360 uses the red as plunging and green as retracting as well.
