### ISSUE TITLE
rephrasing -> Side of Motor Sprockets That Chains Go to Sled

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#686]
https://discourse-cdn-sjc2.com/standard11/uploads/maslowcnc/optimized/2X/9/91c93ae75653c6fba24768ec007da6a190125523_1_637x500.png

Would --> top/bottom chain feed <-- be an option?
The attempt here is to look for a title that jumps to the eye faster.

**Comment by BarbourSmith** [comment]
Yes, I agree that those are the terminology we've agreed on. I will update this right now
