### ISSUE TITLE
Enhancement: Return to 12 o'clock

### ISSUE THREAD

**Issue by madgrizzle** [MaslowCNC/GroundControl#709]
Is it possible during calibration, to have a button that returns the sprockets to their 12 o'clock position?  @davidelang mentioned that after measuring the distance between motors that it might be better to reset everything back to 12 o'clock because people are getting confused and not letting the left chain retract itself.  So, the question is if you set the sprocket at 12 o'clock initially, is it possible to send a command to the firmware to return to directly return to that position.  This would definitely speed up the process since you don't have to wait for the left chain to be retracted by the motors.

**Comment by BarbourSmith** [comment]
Yes! We could absolutely do this.

We know the number of teeth and we know the number of encoder steps per rotation so we can compute degrees moved since 12 and go back

**Comment by madgrizzle** [comment]
So it looks like B06 L0 R0 command tells the FW that both sprockets are at 12 o'clock.  However I was trying to figure out how to tell FW to go to L0 R0 without it having to "rewind".  For example, during the distance between motors measurement, the left sprocket rotates many times to feed out ~3000 mm of chain.  The controller knows the length of the chain that's been fed out but doesn't necessarily know where the 12 o'clock tooth is.  So, would you have to take the 3000 mm and divide it by full revolutions 25.4 mm (one full revolution) yielding 118.1102.  Drop the integer part yields .1102 of a full revolution or 2.8 mm.  So, would you issue a command to retract the left sprocket by a distance of 2.8 mm (put it in relative mode, send the motion command) and then issue  B06 L0 R0 to set it to zero again (because it still thinks its close to 3000.. 3000-2.8)

**Comment by davidelang** [comment]
On Thu, 19 Apr 2018, madgrizzle wrote:

> So it looks like B06 L0 R0 command tells the FW that both sprockets are at 12 
> o'clock.  However I was trying to figure out how to tell FW to go to L0 R0 
> without it having to "rewind".  For example, during the distance between 
> motors measurement, the left sprocket rotates many times to feed out ~3000 mm 
> of chain.  The controller knows the length of the chain that's been fed out 
> but doesn't necessarily know where the 12 o'clock tooth is.  So, would you 
> have to take the 3000 mm and divide it by full revolutions 25.4 mm (one full 
> revolution) yielding 118.1102.  Drop the integer part yields .1102 of a full 
> revolution or 2.8 mm.  So, would you issue a command to retract the left 
> sprocket by a distance of 2.8 mm (put it in relative mode, send the motion 
> command) and then issue B06 L0 R0 to set it to zero again (because it still 
> thinks its close to 3000.. 3000-2.8)

almost.

you take the 3000mm and divide it by one link (6.35 and a correction factor)

so 3000/6.35 = 472.44, drop the integer portion (this is called 'mod' in math, 
and written 3000 % 6.35 = .44 in most programming languages, so you are .44 
links from having a tooth at 12 o'clock

so you can feed in 2.8mm or feed out 3.55mm

**Comment by davidelang** [comment]
On Thu, 19 Apr 2018, madgrizzle wrote:

> This would definitely speed up the process 
> since you don't have to wait for the left chain to be retracted by the motors.

actually, this could slow the process down. is there less movement to retract 
the chain from the distance it was fed out for the motor measurement, or feed it 
out from zero? that depends on if the final location is > 1/2 motor distance 
(not counting the time needed to reposition the chain)

but I think it simplifies the process and doesn't move the motor in what is 
turning out to be an 'unexpected' direction.

**Comment by madgrizzle** [comment]
This would definitely be quicker than the current method of retracting ~3000 mm of chain.  As for the match, I was trying to get the original 12 o'clock tooth back to 12 o'clock, but you are correct in that you just need _a_ tooth at 12 o'clock since you are then resetting it.

**Comment by madgrizzle** [comment]
This can also help those with a chain skip to avoid having to go through the process of setting the tooth at 12 o'clock.  Do it once as accurately as you can and don't touch it again.

**Comment by davidelang** [comment]
On Thu, 19 Apr 2018, madgrizzle wrote:

> This would definitely be quicker than the current method of retracting ~3000 mm of chain

you aren't retracting 3000mm of chain, you are retracting ~1350mm of chain to 
give you a final lenth of 1650mm. This is faster than removing the chain, 
adjusting the sprocket, re-attaching the chain and extending 1650mm of chain.

> As for the match, I was trying to get the original 12 o'clock tooth back to 
> 12 o'clock, but you are correct in that you just need _a_ tooth at 12 o'clock 
> since you are then resetting it.

the sprocket is not 1" (25.4mm) around. I believe it's 11 teeth, so that would 
be just under 70mm around.

**Comment by madgrizzle** [comment]
> you aren't retracting 3000mm of chain, you are retracting ~1350mm of chain to give you a final lenth of 1650mm. This is faster than removing the chain, adjusting the sprocket, re-attaching the chain and extending 1650mm of chain.

Stop being correct.

>the sprocket is not 1" (25.4mm) around. I believe it's 11 teeth, so that would
be just under 70mm around.

I had corrected my math but I suspect you might be replying to an email..  The sprocket has 10 teeth so its 63.5 mm per revolution.. I hope

**Comment by blurfl** [comment]
PR #725 addresses this, can we close?

**Comment by BarbourSmith** [comment]
I had it not work right the other day so I think we should test #725 more to make sure it's working...but I think we can tentatively close this one 👍
