### ISSUE TITLE
all three motors failing 

### ISSUE THREAD

**Issue by slim9263** [MaslowCNC/GroundControl#742]
all three motors not moving . I'm connected to com3 I've reinstalled all software. checked the wires for continuity .They are good read through other threads and checked a number of thing still no luck 

![img_0725](https://user-images.githubusercontent.com/41548895/43048271-459b5c4e-8dd4-11e8-9854-73e14140d926.JPG)

![img_0726](https://user-images.githubusercontent.com/41548895/43048272-45d5dad6-8dd4-11e8-8a7f-f1d5ee1099fa.JPG)

**Comment by slim9263** [comment]
I've gone into Arduino/file/examples/basics/analog read  and analog voltage test and had numbers at 9600 rate
the motors worked yesterday . I shut the machine down in the evening thinking I would try to cut something this morning and found that the motors are not responding  Com3 is not timing out

any help would be appreciated

**Comment by blurfl** [comment]
What do you see when you use Actions/TestMotorsEncoders?

**Comment by slim9263** [comment]
nothing happens  . No pop up sceen

**Comment by slim9263** [comment]
to be more accurate when i click on test motors the action screen disappears and go back to the action/settings screen

**Comment by blurfl** [comment]
I'm hoping you will see either:
• 'Connection Timed Out' message 
![image](https://user-images.githubusercontent.com/1851315/43049874-1cdf63b0-8db4-11e8-95e1-2e52921ba59e.png)

which would indicate the Arduino is not using COM3 or doesn't have the firmware loaded
or 
Something in the GC window that reports the result of the motor test:
![image](https://user-images.githubusercontent.com/1851315/43049877-27731d80-8db4-11e8-8701-d15a831289f8.png)

**Comment by slim9263** [comment]
no it says connected on port com3

**Comment by blurfl** [comment]
And when you do the Action/TestMotorsEncoders, do you se the 
```
G20
B04
Testing L motor:
```
lines?

**Comment by slim9263** [comment]
no when I click the test motor /encoder button it the screen goes back to the previous screen

**Comment by blurfl** [comment]
```
when I click the test motor /encoder button it the screen goes back to the previous screen
```
That's the expected thing, and the progress and results would then get printed on the right side of the screen (see above). It sounds like nothing gets printed when you click though.
 When GC makes the connection to the Arduino, it prints the versions of GC and the firmware - what versions does it show?

**Comment by slim9263** [comment]
doesn't show a version  under the greenplay button it shows
x: 0mm
y: 0mm
z: 0mm
vel: 0 mm/n
 
               connnected
connected on port com3

thats after it click the test motor button

**Comment by blurfl** [comment]
This is a real puzzle!
Do you know what version of GroundControl and firmware you're using? I think you said you had it working a day ago, is the USB cable plugged into the same place on the computer as it was then?

**Comment by slim9263** [comment]
its the newest version and the computer only has one usb port  I tried a different computer and its doing the same thing   I've downloaded the software a couple of times on both comps

**Comment by blurfl** [comment]
I see that you were able to load a different program and see serial output. Try loading the firmware again, and in the Serial Monitor of the Arduino IDE, at 57600 baud, tell us what you see.

**Comment by slim9263** [comment]
Arduino is ver 1.8.5

**Comment by slim9263** [comment]
gc ver 1.17

**Comment by slim9263** [comment]
backwards question marks across the bottom of the screen

**Comment by slim9263** [comment]
backwards question marks across the bottom of the screen
 

    On Sunday, July 22, 2018 6:39 PM, Scott Smith <notifications@github.com> wrote:
 

 I see that you were able to load a different program and see serial output. Try loading the firmware again, and in the Serial Monitor of the Arduino IDE, at 57600 baud, tell us what you see.—

**Comment by blurfl** [comment]
```
backwards question marks across the bottom of the screen
```
Is 57600 selected as in the picture below? The firmware sends text like shown in the picture at 57600 baud. If that's not what you're seeing, we might be on the way to finding the cause.


![image](https://user-images.githubusercontent.com/1851315/43051273-3a1de312-8dcc-11e8-8535-66ec2f40a17c.jpeg)

**Comment by slim9263** [comment]
yes I changed it to 57600 and there are backwards question marks

**Comment by blurfl** [comment]
Ok, the backwards question marks could mean the Arduino is using the wrong baud rate, or that the serial port needs to be reset. 
To fix the baud rate thing, you could upload the firmware to the Arduino again. Check that the Board and Processor selections are set for the Mega 2560:
![image](https://user-images.githubusercontent.com/1851315/43051348-76e72d98-8dcd-11e8-90f2-1c7214a50ba4.png)

To do a full reset to the serial port, do a full power-off shutdown of the PC and start it up again - a tedious thing, but sometimes a helpful thing to try.

**Comment by slim9263** [comment]
ok ive done that already but ill do it again  so uninstall Arduino then reinstall  then shut down comp

**Comment by blurfl** [comment]
Don't need to uninstall Arduino, just open the cnc_ctrl_v1.ino file again, and upload to the Arduino Mega 2560 board.

**Comment by blurfl** [comment]
When the upload is done, we're looking for the 'Done loading' message near the bottom of the window. When you see that, you could again check the Serial Monitor at 57600 baud to see if the serial stream looks like my picture above. If not, the power-off reboot would be next...


![image](https://user-images.githubusercontent.com/1851315/43051504-e72b1f22-8dcf-11e8-9146-cddacb620098.png)

**Comment by slim9263** [comment]
ok that worked  the motors are turning then tested  now it says unable to find valid machine position for chain length

**Comment by blurfl** [comment]
💯🎉👍 Great news!
 The chain calibration was lost when a non-Maslow program was loaded into the Arduino. All that is needed to solve that is to do the Actions/SetChainLength-Automatic sequence. You're almost there...

**Comment by slim9263** [comment]
ok thank you so much  I owe you a coffee  all three motors are working   chain is calibrated  I hope this thread helps someone else

**Comment by blurfl** [comment]
```
I hope this thread helps someone else
```
It will help the next one, thanks for being so patient. Many happy wood chips to you!
