### ISSUE TITLE
Macafee sequestering GCode files

### ISSUE THREAD

**Issue by ejsrdenny** [MaslowCNC/GroundControl#748]
Macafee is sequestering two files from GCODE version 1.18 which prevents it from running. Just looking to see if anyone else is having this problem and if there is confidence that I can unsequester the files without putting the rest of my computer at risk.

here are the flagged files.
![image](https://user-images.githubusercontent.com/42008640/43540466-0b04e088-9585-11e8-8af5-7afd1b82699e.png)

**Comment by ejsrdenny** [comment]
McAfee does not give any information, but it prevents GCODE from running. I will unsequester it and report back.

**Comment by blurfl** [comment]
If you like, you could cross-check the suspect log file at [Kasperski VirusDesk](https://virusdesk.kaspersky.com/#scanresults). I've checked the file from my system, it comes out as safe. Yours might be different.

**Comment by blurfl** [comment]
Any update on this? did you get GC running?

**Comment by ejsrdenny** [comment]
I did get ground control running, but only after turning off real time scan. Do you think it's because GCODE executes from a .bat file
