### ISSUE TITLE
Cut 4 in the triangular kinematics test pattern failed

### ISSUE THREAD

**Issue by shutej** [MaslowCNC/GroundControl#772]
When doing calibration, the triangular kinematic makes 5 cuts.  The router made cuts 1, 3, 5, 2 but then froze at cut 4 with the bit suspended in mid-air, without plunging the bit into the board to make the final cut.  It's not clear what happened from the user interface.

I'm using a Raspberry Pi 3 model B (not B+), configured with a Raspberry Pi touchscreen (and a recent rpi-update run to bring both kernel and firmware up-to-date). It's running Ubuntu MATE 16.04 (with all updates installed) with Kivy, GroundControl, and firmware all installed from source as of several days ago.

In general, I'd love some visual indication of what each problem is, when it's encountered.  Is there a debug mode that catches all top-level exceptions in all threads and displays them to the screen?

**Comment by blurfl** [comment]
There is a log file - log.txt, in the same directory as main.py. It’s guppy’s of chatter, but you can filter that out in a text editor or using grep. It’s a record of what is sent and received from the GC end of things.

**Comment by shutej** [comment]
OK I'm using SSH to watch the log file. How do I skip through the steps of calibration? The skip button doesn't seem to have any effect (including on the screen, in the log file, or indeed on the terminal).

**Comment by blurfl** [comment]
I don't have experience with GC on a RPi/touchscreen ; the 'Skip' button is what you want, is there a chance you could hook up a mouse to see if that makes 'Skip' work?

**Comment by shutej** [comment]
The solution to this problem (and many others) was to not use a Raspberry Pi but, instead, use a laptop.
