### ISSUE TITLE
click and drag outside the Z window crasches GC

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/GroundControl#780]
As posted here https://forums.maslowcnc.com/t/zaxis-gc-close-out/7274
there is a bug crashing GC, confirmed with Windows and Ubuntu.
With GC 1.23 and back to GC 1.03

To replicate:
Open the Z menu, click and drag outside the Z window.

Credit for finding goes to TalleyMakeWork

**Comment by BarbourSmith** [comment]
This sounds like something I should fix. I'm going to assign it to my self and jump on it!

**Comment by BarbourSmith** [comment]
It looks like the issue actually happens when clicking and dragging outside any popup

**Comment by GeroBH** [comment]
That was fast, guess 3 confirmed tests should be enough to close.
