### ISSUE TITLE
not displaying correctly in linux mint.

### ISSUE THREAD

**Issue by robcnc2019** [MaslowCNC/GroundControl#792]
think this may be a problem with flash plugin as I've tried using firefox and chromium, in both instances just below where you would enable the flash plugin are the words about this... and there is no where to clear it from the screen, at first I though it may be related to the page zoom function built into the browser, but tried zooming in and out to no effect. as a precaution I tried PARTKAM and that displays correctly. I use makercam almost daily so it's a recent issue, possibly related to an update, if you have updated the software in the last 2-3 days.

**Comment by BarbourSmith** [comment]
Unfortunately I don't actually control MakerCAM 😁 It's just a website run by someone else out there 😛

**Comment by robcnc2019** [comment]
Ah, that's a shame, I guess I will just have to use partkam, seems to me there is not much difference between the two anyway. Thanks for letting me know. 

    On Wednesday, 1 May 2019, 01:19:58 BST, BarbourSmith <notifications@github.com> wrote:  
 
 
Unfortunately I don't actually control MakerCAM 😁 It's just a website run by someone else out there 😛
