### ISSUE TITLE
Z-Axis calibration for Bosch 1617 Router Base

### ISSUE THREAD

**Issue by trakru** [MaslowCNC/GroundControl#793]
**Issue**: Z-axis calibration for Bosch 1617 Router Base. "Plunge to -1.000" button on the calibration page raises the router bit instead of depressing it into the workpiece

**System Config**:

- Ground Control v 1.26
- Maslow Firmware v 1.26
- Ubuntu 18.04.2 LTS

Pitch value was changed to -1.5 based on suggestions in the Maslow forums. this resolved the "Relative Raise/Lower" buttons to work as expected. 

Clicking Lower, lowers the router bit. Terminal Log:

> G91 G00 Z-1.0 G90

Clicking "Plunge" raises the router bit. Terminal Log

> G91 G00 Z1.000 G90

**Comment by GeroBH** [comment]
Forum post:
https://forums.maslowcnc.com/t/shaft-coupler-for-bosch-1617/4372/23

**Comment by BarbourSmith** [comment]
So is this still an open issue in Ground Control? If so I can work on a fix

**Comment by GeroBH** [comment]
I was not able to replicate the issue in Fake-Server mode. FW/GC 1.26
Having a negative or a positive pitch in the setting gives me the expected results in the GC simulation.

> Clicking "Plunge" raises the router bit. Terminal Log
    G91 G00 Z1.000 G90

Is not the correct line from the terminal.
it should be
`G00 Z-1.0`

If the bit is lower then -1 it raises, if it is higher it it lowers to the absolute position Z-1.
It's hard to see with the Z-menu open, but possible.
Does the Z value in GC change to Z-1?
![image](https://user-images.githubusercontent.com/25812652/57448806-fab46a80-7262-11e9-97c4-7def4e240a54.png)

**Comment by trakru** [comment]
i agree, i dont see the same issue anymore. Clicking Plunge does lower the router bit

![Screenshot from 2019-05-09 15-36-40](https://user-images.githubusercontent.com/3015454/57481524-52a59e00-7270-11e9-95f2-a5a6af485ae9.png)

As you can see, the correct plunge command is going through the terminal. I am not sure what/why happened, but i guess we can close this issue

**Comment by trakru** [comment]
I ended up calibrating the machine successfully after realising that clicking the define zero button takes the Z-axis UP by +5 mm. Made sure that much tolerance was present before clicking Define Zero and that helped complete the process. Just noting for future purposes
