### ISSUE TITLE
need to restart release process

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/GroundControl#795]
no releases have happened since January

We need to document (if not automate) the release process and make it so multiple people can make the release.

**Comment by blurfl** [comment]
Not much has changed here since the last release... The changes over in Firmware have been mostly cosmetic.

**Comment by blurfl** [comment]
It looks to me like releasing GC v1.27 at this point would capture:

> Merged #789 Change default extend chain length to 1651 mm 
> Merged #794 Clean up serialPortThread() connection handshake

**Comment by BarbourSmith** [comment]
I just want to follow up that I've heard back from the Maker Made folks today that things are good on their end. I don't think it's worth waiting any longer to hear back from everyone. I vote we release here so we can keep moving forwards. Any opposition?

**Comment by blurfl** [comment]
Sounds good to me. Thanks for taking care of contacting the vendors.

**Comment by BarbourSmith** [comment]
Release has been released! 🎉
