### ISSUE TITLE
Just blank screen when opening ground control

### ISSUE THREAD

**Issue by mattrammo** [MaslowCNC/GroundControl#803]
Just blank screen when opening ground control
![image](https://user-images.githubusercontent.com/54548696/63708022-0345a680-c83c-11e9-999b-abddae857210.png)

**Comment by BarbourSmith** [comment]
I'm pretty stumped on this one, but I've made a post in the [Kivy users forum](https://kivy.org/?place=forum%2Fkivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Fkivy.org%2F%23#forum) asking for help. Hopefully someone will get back to me soon.

**Comment by mattrammo** [comment]
yes GPU driver update did the treat

**Comment by blurfl** [comment]
Thanks for posting your solution. Can this be closed?
