### ISSUE TITLE
Scaling problems from Gcode

### ISSUE THREAD

**Issue by tlohnes66** [MaslowCNC/GroundControl#814]
I'm getting gcode on GroundControl I created in both MakerCAM and FreeCAM that doesn't measure the same as what I started with; sometimes it's larger, sometimes smaller.  I've already tried making sure I set the pixels at 96 in MakerCAM, but this happens when I make a project from scratch in FreeCAM as well.  I'm tired of scaling over and over and still getting it wrong.  Much sawdust with little to show for it.  HELP! All I want to do is cut something the same size as what I built on the screen.  Shouldn't be this hard. I know I'm a noob at this, so there has to be something I'm doing wrong in both programs.

**Comment by BarbourSmith** [comment]
Is the issue that when you cut a square it comes out with one side larger than the other, or does the whole square come out too big? If you were to cut a 4 inch square what are the measurements of each side?

**Comment by tlohnes66** [comment]
I just cut a square that was measured at 3.38 inches on the groundcontrol
screen (translated from mm by comparing points) but it cuts at 3x3.
Terry Lohnes
503-913-9838
terry.d.lohnes@gmail.com
*www.linkedin.com/in/terrydlohnes* <http://www.linkedin.com/in/terrydlohnes>

**Comment by tlohnes66** [comment]
From FreeCAD using grbl_post to make the gcode file I made a 4x4 box which
cut at 3 7/8" wide by 4 1/4" tall.

Terry Lohnes
503-913-9838
terry.d.lohnes@gmail.com
*www.linkedin.com/in/terrydlohnes* <http://www.linkedin.com/in/terrydlohnes>

**Comment by BarbourSmith** [comment]
Hmmmm now I am more confused 😀 

If you were getting distorted shapes like the second case I was going to say it is a calibration issue (and that is still my first guess)...however the fact that your first shape came out 3x3 seems to indicate a software issue in generating the gcode because distortion almost never produces symmetrical shapes

**Comment by tlohnes66** [comment]
It may have to do with MakerCAM also. On the first cut I used MakerCAM on a
part I've been trying to get right for a week now, and on the second cut I
created a 4x4 job in FreeCAD(which I'm still very new at). I'm moving away
from MakerCAM anyway, so I'll focus on FreeCAD.  What do you suggest for
calibration? Thanks in advance for your help!


On Feb 6, 2020 at 10:13 PM, BarbourSmith <notifications@github.com> wrote:

Hmmmm now I am more confused 😀

If you were getting distorted shapes like the second case I was going to
say it is a calibration issue (and that is still my first guess)...however
the fact that your first shape came out 3x3 seems to indicate a software
issue in generating the gcode because distortion almost never produces
symmetrical shapes

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MaslowCNC/GroundControl/issues/814?email_source=notifications&email_token=AOPRL72VNPMIG3DDGQ263ZDRBT3ZZA5CNFSM4KRDV3XKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELB3BYA#issuecomment-583250144>,
or unsubscribe

**Comment by BarbourSmith** [comment]
Calibration can be tricky and I think is the biggest drawback of the current design.

Are you a member of the forums? https://forums.maslowcnc.com/

You can find a lot more information about calibration over there. Not so many people follow this space since it's really just for tracking Ground Control software bugs.

Were you able to complete the calibration process successfully?

**Comment by tlohnes66** [comment]
I just signed up to be a member of Maslow forums. I did go through the
calibration process when I put the Maslow together but not since. Do you
recommend I start from scratch?


On Feb 7, 2020 at 8:39 AM, BarbourSmith <notifications@github.com> wrote:

Calibration can be tricky and I think is the biggest drawback of the
current design.

Are you a member of the forums? https://forums.maslowcnc.com/

You can find a lot more information about calibration over there. Not so
many people follow this space since it's really just for tracking Ground
Control software bugs.

Were you able to complete the calibration process successfully?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MaslowCNC/GroundControl/issues/814?email_source=notifications&email_token=AOPRL76PHKVD24QC4XYR3FLRBWFFTA5CNFSM4KRDV3XKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELDVXHY#issuecomment-583490463>,
or unsubscribe

**Comment by BarbourSmith** [comment]
Were you previously getting accurate shapes?

If you felt the calibration process went well initially, then I would go through just the short process under **Actions -> Set Chain Lengths Automatic** which will reset the chain lengths which is quick and could be causing the behavior you are seeing.

**Comment by tlohnes66** [comment]
So I went through the calibration process again and then cut the same 4"
square.  It is now symmetrical and within a 32nd of 4". How often should I
re-calibrate it? Once a day when I'm cutting? before each cut?

thanks,
Terry

**Comment by BarbourSmith** [comment]
Excellent! You should never have to calibrate again unless you disassemble and reassemble the machine 😁

If you take the chains off for some reason and want to put them back on use Actions -> Set Chain Lengths Automatic

**Comment by tlohnes66** [comment]
I'm working on a Meticulous Z-axis sled so I'll set chain length again
after that.  Thanks for all your help!
Terry


On Feb 9, 2020 at 2:35 PM, BarbourSmith <notifications@github.com> wrote:

Excellent! You should never have to calibrate again unless you disassemble
and reassemble the machine 😁

If you take the chains off for some reason and want to put them back on use
Actions -> Set Chain Lengths Automatic

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MaslowCNC/GroundControl/issues/814?email_source=notifications&email_token=AOPRL7YW3ZZXZZS7XZUNAIDRCCALTA5CNFSM4KRDV3XKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELG2IFA#issuecomment-583902228>,
or unsubscribe

**Comment by BarbourSmith** [comment]
Absolutely! Happy to help
