### ISSUE TITLE
Link to WebControl

### ISSUE THREAD

**Issue by niccokunzmann** [MaslowCNC/GroundControl#828]
https://github.com/MaslowCNC/GroundControl/blob/master/INSTRUCTIONS.md mentions "WebControl" but I would like to see this as a link so I can have a look at it.

**Comment by joeldfsutton** [comment]
https://github.com/WebControlCNC/WebControl

**Comment by BarbourSmith** [comment]
I've made the reference in the documentation a link too. Great suggestion! Good to close this issue?

**Comment by niccokunzmann** [comment]
thanks!
