### ISSUE TITLE
Connection TimeOut

### ISSUE THREAD

**Issue by Gamafam6** [MaslowCNC/GroundControl#830]
When trying to connect to my port I am receiving a Connection Time Out error. Another error getting received is from Ground Control and it states: It is possible that the serial port selected is not the one used by Maslow's Arduino or that the firmware is not loaded on the Arduino. Connected on port COM4 Connection Timed Out. 

If anyone has come across this issue please let me know how you fixed it.

Thank you.
![Maslow Error](https://user-images.githubusercontent.com/121466420/209593902-34b84e98-8e33-4c7f-8aee-0c14b9393ff3.PNG)
 I did update my software to the latest version.

**Comment by Gamafam6** [comment]
Just as a note I have the Maslow Maker Made CNC Basic Bundle

**Comment by BarbourSmith** [comment]
Welcome!

I think that for the Maker Made controller you need to use their Makerverse software. I believe that Ground Control will not work with their controller 😞

**Comment by Gamafam6** [comment]
Thank you, I did try updating the software and now I’m receiving error message in arduino “compilation terminated exit status 1 Maslow h no such file or directory”. Not sure if you have come across this error

**Comment by BarbourSmith** [comment]
That error usually comes from the zip file not being extracted...BUT more than that I believe that the Maker Made controller only works with their firmware and their software which is different from this one

**Comment by Gamafam6** [comment]
Hello,
I’m having issues with my Z axis from the M2 Maslow. It either goes too high or too low. I have tried multiple times to calibrate it and that does not fix the problem. 

Please let me know what else I am able to do to get my Maslow working properly again. 

Antoinette 

Sent from my iPhone

**Comment by BarbourSmith** [comment]
Welcome! 

This isn't really the right place for that question because the M2 doesn't actually use this software. I would try posting in the forums here: https://forums.maslowcnc.com/
